DataBundle\Entity\Car:
    properties:
        name:
            - NotBlank: ~

DataBundle\Entity\PetrolStation:
    constraints:
            - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~

DataBundle\Entity\FuelType:
    constraints:
            - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~

DataBundle\Entity\Refuel:
    properties:
        date:
            - NotBlank: ~
        carDistance:
            - NotBlank: ~
        unitPrice:
            - NotBlank: ~
        amountPurchased:
            - NotBlank: ~
        type:
            - NotBlank: ~
        car:
            - NotBlank: ~
        petrolStation:
            - NotBlank: ~
