DataBundle\Entity\Refuel:
  exclusion_policy: ALL
  xml_root_name: refuel
  properties:
    id:
      expose: true
    date:
      expose: true
    carDistance:
      expose: true
      serialized_name: "carDistance"
    unitPrice:
      expose: true
      serialized_name: "unitPrice"
    amountPurchased:
      expose: true
      serialized_name: "amountPurchased"
    type:
      expose: true
      type: DataBundle\Entity\FuelType
    petrolStation:
      expose: true
      type: DataBundle\Entity\PetrolStation
      serialized_name: "petrolStation"