car:
  type: rest
  resource: "@RestAPIBundle/Controller/CarController.php"

refuel:
  type: rest
  parent: car
  resource: "@RestAPIBundle/Controller/ReFuelController.php"

fuel_type:
  type: rest
  resource: "@RestAPIBundle/Controller/FuelTypeController.php"

petrol_station:
  type: rest
  resource: "@RestAPIBundle/Controller/PetrolStationController.php"
