<?php

namespace DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PetrolStationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PetrolStationRepository extends EntityRepository
{
}
